spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dfd
    username: dfdUser
    password: dfd2025*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always